# Generated by Django 3.1.5 on 2021-01-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=30)),
                ('job_description', models.CharField(max_length=30)),
                ('job_type', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('experience', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=20)),
                ('expiry_date', models.CharField(max_length=20)),
            ],
        ),
    ]
