# Generated by Django 3.1.5 on 2021-01-22 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
