# Generated by Django 3.1.5 on 2021-01-08 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210107_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
