# Generated by Django 3.1.5 on 2021-01-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210122_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='type',
            new_name='userType',
        ),
    ]
