# Generated by Django 3.1.6 on 2021-03-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_job_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_category',
            field=models.CharField(choices=[('finance', 'Finance'), ('marketing', 'Marketing'), ('webdesign', 'Webdesign'), ('accountant', 'Accountant'), ('others', 'Others')], default='others', max_length=250),
        ),
    ]
