# Generated by Django 3.1.6 on 2021-03-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210302_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='id',
            new_name='job_id',
        ),
    ]
