# Generated by Django 3.1.6 on 2021-03-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_savedjobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedjobs',
            old_name='payment_id',
            new_name='job_employer',
        ),
        migrations.RenameField(
            model_name='savedjobs',
            old_name='payment_type',
            new_name='job_phone',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='active',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='order_date',
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='job_category',
            field=models.CharField(default=True, max_length=250),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='job_description',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='job_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='job_position',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='job_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='job_website',
            field=models.URLField(null=True),
        ),
    ]
