# Generated by Django 3.1.6 on 2021-03-03 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0012_auto_20210302_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_email',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_employer',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_phone',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_position',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='job_website',
        ),
        migrations.AddField(
            model_name='savedjobs',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.job'),
        ),
        migrations.AlterField(
            model_name='savedjobs',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
