# Generated by Django 3.1.6 on 2021-03-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_appliedjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruiterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyEmail', models.CharField(max_length=15, null=True)),
                ('CompnayName', models.CharField(max_length=10, null=True)),
                ('Location', models.CharField(max_length=15, null=True)),
                ('CompanyType', models.CharField(max_length=15, null=True)),
                ('contactNumber', models.CharField(max_length=15, null=True)),
                ('location', models.CharField(max_length=15, null=True)),
                ('personalName', models.CharField(max_length=15, null=True)),
                ('personalContact', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
