# Generated by Django 3.1.6 on 2021-03-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_recruiterdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterdetails',
            name='location',
        ),
    ]
