# Generated by Django 3.1.6 on 2021-03-20 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20210319_1809'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recruiterDetails',
        ),
    ]
