# Generated by Django 3.1.6 on 2021-03-20 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_delete_recruiterdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='recruiterDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userTypes', models.CharField(max_length=15, null=True)),
                ('Location', models.CharField(max_length=15, null=True)),
                ('CompanyType', models.CharField(max_length=15, null=True)),
                ('personalName', models.CharField(max_length=15, null=True)),
                ('personalContact', models.CharField(max_length=15, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
