# Generated by Django 3.1.6 on 2021-03-20 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_recruiterdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterdetails',
            name='Location',
        ),
    ]
