# Generated by Django 3.1.6 on 2021-03-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_recruiterdetails_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterdetails',
            name='Location',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
