# Generated by Django 3.1.6 on 2021-03-20 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_recruiterdetails_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='recruiterDetails',
        ),
    ]
