# Generated by Django 3.1.6 on 2021-03-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_auto_20210320_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterdetails',
            old_name='userTypes',
            new_name='userType',
        ),
    ]
