# Generated by Django 3.1.6 on 2021-03-20 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_recruiterdetails_contactnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterdetails',
            old_name='userType',
            new_name='userTypes',
        ),
    ]
