# Generated by Django 3.1.6 on 2021-03-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20210320_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterdetails',
            name='CompanyName',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
