# Generated by Django 3.1.6 on 2021-03-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_recruiterdetails_companyname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiterdetails',
            old_name='CompnayEmail',
            new_name='CompanyEmail',
        ),
    ]
