# Generated by Django 3.1.6 on 2021-03-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210321_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterdetails',
            name='companyDetails',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
