# Generated by Django 3.1.6 on 2021-04-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_remove_client_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='cvImages',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
